if ISL_VERSION == nil then
    ISL_TYPE = "HD"
    ISL_BUILD = "241222a"

    ISL_VERSION = "121-"..ISL_BUILD.."-"..ISL_TYPE

    LOG("IMPROVED STORYLINE V1.2.1 "..ISL_TYPE.." BUILD "..ISL_BUILD)
end